### ISSUE TITLE
Crash: osmdroid in recyclerview: java.lang.IllegalStateException: Too many receivers, total of 1000

### ISSUE THREAD

**Issue by skyerjoe** [mh-/corona-warn-companion-android#138] opened 2022-01-04 20:41 UTC
Device: Xiaomi mi9tpro 
Rooted: no  
Os:  mui 12.5.1  based on Android 11
Cctg:  2.14.1.0

Mode: Export through cctg

When i try to browse in the matching results the screen suddenly appears black for a few secs (looks  like standby)  and then the  matching process will be starting again from the beginning. 

Best regards. John

**Comment by skyerjoe** [comment] 2022-01-06 14:36
I updated to 2.1.3 but the issue still exist 
When i have to guess may its related to hibernation processes from some Chinese OS'es which give a f** on the Android guidelines for apps which are opaerate in standby mode.

**Comment by r00t-** [comment] 2022-01-07 16:53
had just written this up before i saw you put up a new release, which i'm testing now...
(was also unsure where to post my report, as there seem to be so many duplicates already.)

i'm also seeing crashes during analysis. (also on a xiaomi device.)
this appears to have started with the new year (at least i did not install any updates or anything like that, and never saw a crash in december).
it appears to be related to the reliability of the network connection? it appears that i see more crashes when on a low-quality network connection, when i tried on my home wifi it suddenly worked. (or maybe that was because it was past midnight, and less hourly files had to be pulled into the analysis?)
i looked at logcat, and everytime it seems the process is killed due to out-of-memory.
(attaching an example.: [oom_22:24.txt](https://github.com/mh-/corona-warn-companion-android/files/7830076/oom_22.24.txt) )

**Comment by mh-** [comment] 2022-01-07 17:15
**For the problem where the app crashes because of out-of-memory when showing days with many encounters - it would help me a lot if someone could send me a database that reproducibly crashes.**

**Comment by ginkel** [comment] 2022-01-07 17:25
> **For the problem where the app crashes because of out-of-memory when showing days with many encounters - it would help me a lot if someone could send me a database that reproducibly crashes.**

Done. Hope it helps, it's not 100% reproducible for me...

**Comment by skyerjoe** [comment] 2022-01-07 18:53
@mh-  I  can  also send u the db after crashing did u mean this ? 
How could i send u the db file ?

**Comment by mh-** [comment] 2022-01-07 19:01
I was looking for a large database with many risk encounters. I got one now, it took my poor cheap Android device about an hour to find all the matches... However it didn't crash yet. So if you have a db that causes the Warn Companion app to always crash, it would help me to find out what to do about it...
To send it to me, e-mail is one option: warn-app-companion@tosl.org

**Comment by skyerjoe** [comment] 2022-01-07 19:09
Sended   !!!!

**Comment by skyerjoe** [comment] 2022-01-09 18:31
@mh- 

I've created strace crash log with an help of an app  may this also helps to figure out the issue   
I'm not so familar with logcat etc. if u need more or sth else give me FB. 

Crash Strace Log WAC ( CWC): 
```
FATAL EXCEPTION: main
Process: org.tosl.coronawarncompanion, PID: 11655
android.view.InflateException: Binary XML file line #74 in org.tosl.coronawarncompanion:layout/match_card_fragment: Binary XML file line #74 in org.tosl.coronawarncompanion:layout/match_card_fragment: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #74 in org.tosl.coronawarncompanion:layout/match_card_fragment: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:856)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:963)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1125)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1086)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:684)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
	at org.tosl.coronawarncompanion.matchentries.MatchesRecyclerViewAdapter.onCreateViewHolder(MatchesRecyclerViewAdapter.java:116)
	at org.tosl.coronawarncompanion.matchentries.MatchesRecyclerViewAdapter.onCreateViewHolder(MatchesRecyclerViewAdapter.java:81)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8061)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 11655, callerPackage: org.tosl.coronawarncompanion
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2384)
	at android.os.Parcel.createException(Parcel.java:2360)
	at android.os.Parcel.readException(Parcel.java:2343)
	at android.os.Parcel.readException(Parcel.java:2285)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5634)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1636)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1590)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1578)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:679)
	at org.osmdroid.tileprovider.util.SimpleRegisterReceiver.registerReceiver(SimpleRegisterReceiver.java:21)
	at org.osmdroid.tileprovider.modules.MapTileFileStorageProviderBase.<init>(MapTileFileStorageProviderBase.java:26)
	at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider.<init>(MapTileSqlCacheProvider.java:55)
	at org.osmdroid.tileprovider.MapTileProviderBasic.getMapTileFileStorageProviderBase(MapTileProviderBasic.java:189)
	at org.osmdroid.tileprovider.MapTileProviderBasic.<init>(MapTileProviderBasic.java:97)
	at org.osmdroid.tileprovider.MapTileProviderBasic.<init>(MapTileProviderBasic.java:70)
	at org.osmdroid.tileprovider.MapTileProviderBasic.<init>(MapTileProviderBasic.java:63)
	at org.osmdroid.views.MapView.<init>(MapView.java:224)
	at org.osmdroid.views.MapView.<init>(MapView.java:200)
	at org.osmdroid.views.MapView.<init>(MapView.java:260)
	... 25 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:16190)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2257)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2981)
	at android.os.Binder.execTransactInternal(Binder.java:1157)
	at android.os.Binder.execTransact(Binder.java:1126)
```

**Comment by mh-** [comment] 2022-01-09 18:42
@uhengart Any idea what may cause this?

**Comment by mh-** [comment] 2022-01-09 18:56
I can reliably reproduce this by
1) use a RaMBLE database with a few matches on one day
2) tap on that day after matching
3) activate "show maps"
4) scroll up and down many times.

In step 4) the RecyclerView will call osmdroid many times, and apparently org.osmdroid.tileprovider.util.SimpleRegisterReceiver.registerReceiver(SimpleRegisterReceiver.java:21) will be called 1000 times without de-registering in between.

**Comment by mh-** [comment] 2022-01-09 22:22
Hopefully fixed by https://github.com/mh-/corona-warn-companion-android/commit/3611e8001e30d33086cdc87ffc574bdc2ce485de in https://github.com/mh-/corona-warn-companion-android/releases/tag/2.3.1

**Comment by skyerjoe** [comment] 2022-01-09 23:09
Feedback 2.3.1:
The Scrolling Problem seems fixed.
It feels like a little bit slower during the matching process.

And some Date Gaps in the matching  view:

![IMG_20220110_000440](https://user-images.githubusercontent.com/1038130/148704976-cfa1060b-4430-410d-b6e7-6563e62545df.jpg)

**Comment by mh-** [comment] 2022-01-10 06:44
Yes, I think that's normal.

Closed with https://github.com/mh-/corona-warn-companion-android/commit/3611e8001e30d33086cdc87ffc574bdc2ce485de

**Closed by mh-** 2022-01-10 06:44 UTC
Labels: bug
